# Generated by Django 5.1.7 on 2025-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='main_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ramp_pair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbookings',
            name='main_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbookings',
            name='ramp_pair',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
